import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import CommonSection from "@/components/CommonSection";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Navbar />
        <main className="relative overflow-hidden">{children}</main>
        <Footer />
        
      </body>
    </html>
  );
}
